import { useState, useEffect, useMemo } from 'react';
import { useToast } from '../components/Toast';
import api from '../services/api';
import Icon from '../components/Icon';
import { exportCSV, exportExcel, exportImage } from '../utils/exportReport';

const DAY_NAMES = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
const ORDINALS = ['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th'];

const statusMeta = {
  present: { label: 'Present', cls: 'present', icon: 'check' },
  late: { label: 'Late', cls: 'late', icon: 'clock' },
  pending: { label: 'Pending', cls: 'pending', icon: 'clock' },
  approved: { label: 'Approved', cls: 'approved', icon: 'check' },
  rejected: { label: 'Rejected', cls: 'rejected', icon: 'x' },
  absent: { label: 'Absent', cls: 'absent', icon: 'x' },
};

const presenceMeta = {
  present: { label: 'Present', cls: 'present', icon: 'check' },
  late: { label: 'Late', cls: 'late', icon: 'clock' },
  absent: { label: 'Absent', cls: 'absent', icon: 'x' },
};

const PRESENCE_OPTIONS = [
  { value: '', label: 'All Presence' },
  { value: 'present', label: 'Present' },
  { value: 'late', label: 'Late' },
  { value: 'absent', label: 'Absent' },
];

function toDateISO(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

const MY_HEADERS = ['Date', 'Class', 'Subject', 'Day', 'Period', 'Presence', 'Status', 'Marked At', 'Approved By'];

// Student: self view of their own attendance (approved/rejected/pending counts
// over a selected number of days) with Excel / CSV / image export.
function MyAttendance() {
  const showToast = useToast();
  const [records, setRecords] = useState([]);
  const [student, setStudent] = useState(null);
  const [loading, setLoading] = useState(true);
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [presence, setPresence] = useState('');

  useEffect(() => {
    if (!fromDate || !toDate) {
      setFromDate(toDateISO(new Date(Date.now() - 30 * 86400000)));
      setToDate(toDateISO(new Date()));
    }
  }, [fromDate, toDate]);

  const load = async () => {
    setLoading(true);
    try {
      const data = await api.getMyAttendance();
      setRecords(data.records || []);
      setStudent(data.student || null);
    } catch (err) {
      showToast(err.message, 'error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const filtered = useMemo(() =>
    records.filter(r =>
      (!fromDate || r.scheduledDate >= fromDate) && (!toDate || r.scheduledDate <= toDate) &&
      (!presence || r.presence === presence)
    ).sort((a, b) => (b.scheduledDate || '').localeCompare(a.scheduledDate || '') || a.periodIndex - b.periodIndex),
  [records, fromDate, toDate, presence]);

  const summary = useMemo(() => {
    const total = filtered.length;
    const present = filtered.filter(r => r.presence === 'present' || r.status === 'approved').length;
    const late = filtered.filter(r => r.presence === 'late' || r.status === 'late').length;
    const absent = filtered.filter(r => r.presence === 'absent' || r.status === 'rejected').length;
    const pending = filtered.filter(r => r.status === 'pending').length;
    const approved = filtered.filter(r => r.status === 'approved').length;
    const rate = total > 0 ? Math.round(((present + late) / total) * 100) : 0;
    return { total, present, late, absent, pending, approved, rate };
  }, [filtered]);

  const exportRows = useMemo(() => filtered.map(r => [
    r.scheduledDate,
    r.className || '',
    r.subject || '—',
    r.day || '',
    `${ORDINALS[r.periodIndex] || (r.periodIndex + 1) + 'th'}`,
    presenceMeta[r.presence]?.label || 'Present',
    (r.status === 'absent' || r.presence === 'absent') ? '—' : (statusMeta[r.status]?.label || r.status),
    r.markedAt || '',
    r.approvedBy || '—',
  ]), [filtered]);

  const fileStem = `my_attendance_${(student?.name || 'student').replace(/[^a-zA-Z0-9_-]/g, '_')}_${fromDate}_${toDate}`;
  const footer = `Generated by NCBA & E Student Management System on ${new Date().toLocaleString()}`;

  const handleExport = (type) => {
    if (filtered.length === 0) { showToast('No data to export yet', 'info'); return; }
    try {
      if (type === 'csv') {
        exportCSV(`${fileStem}.csv`, MY_HEADERS, exportRows);
      } else if (type === 'excel') {
        exportExcel(`${fileStem}.xlsx`, MY_HEADERS, exportRows);
      } else {
        exportImage(`${fileStem}.png`, {
          title: `My Attendance — ${student?.name || 'Student'}`,
          subtitle: `Class ${student?.className || '—'} • ${fromDate} to ${toDate} • ${filtered.length} record(s)`,
          footer,
          headers: MY_HEADERS,
          rows: exportRows,
        });
      }
      showToast(`Attendance exported as ${type.toUpperCase()}.`);
    } catch (err) {
      showToast(err.message || 'Export failed', 'error');
    }
  };

  return (
    <div>
      <div className="page-header">
        <h1>My Attendance</h1>
        <p>
          {student ? `${student.name} — ${student.className || 'Class not assigned'}` : 'Your attendance history'}.
          Present / Late / Absent for the selected number of days.
        </p>
      </div>

      {/* Filters */}
      <div className="card" style={{ padding: '16px 20px', marginBottom: '20px' }}>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(170px, 1fr))', gap: '14px', alignItems: 'end' }}>
          <div className="form-group" style={{ margin: 0 }}>
            <label>From Date</label>
            <input type="date" value={fromDate} onChange={e => setFromDate(e.target.value)} />
          </div>
          <div className="form-group" style={{ margin: 0 }}>
            <label>To Date</label>
            <input type="date" value={toDate} onChange={e => setToDate(e.target.value)} />
          </div>
          <div className="form-group" style={{ margin: 0 }}>
            <label>Presence</label>
            <select value={presence} onChange={e => setPresence(e.target.value)}>
              {PRESENCE_OPTIONS.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
            </select>
          </div>
          <div className="form-group" style={{ margin: 0 }}>
            <label>&nbsp;</label>
            <span style={{ fontSize: '0.82rem', color: 'var(--gray)' }}>
              Showing {filtered.length} of {records.length} record(s).
            </span>
          </div>
        </div>
      </div>

      {/* Summary cards */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(140px, 1fr))', gap: '12px', marginBottom: '20px' }}>
        {[
          { label: 'Total Days', value: summary.total, color: 'var(--primary)' },
          { label: 'Present', value: summary.present, color: 'var(--success)' },
          { label: 'Late', value: summary.late, color: 'var(--warning)' },
          { label: 'Absent', value: summary.absent, color: 'var(--danger)' },
          { label: 'Pending', value: summary.pending, color: 'var(--info)' },
          { label: 'Attendance', value: `${summary.rate}%`, color: 'var(--primary)' },
        ].map(s => (
          <div key={s.label} className="card" style={{ padding: '14px 16px', textAlign: 'center' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: '700', color: s.color }}>{s.value}</div>
            <div style={{ fontSize: '0.72rem', color: 'var(--gray)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>{s.label}</div>
          </div>
        ))}
      </div>

      {/* Export bar */}
      <div className="panel" style={{ marginBottom: '20px' }}>
        <div className="panel-header">
          <h3><Icon name="document" size={18} /> Export My Attendance</h3>
          <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
            <button className="btn btn-secondary" onClick={() => handleExport('excel')} style={{ padding: '8px 14px' }}>
              <Icon name="download" size={14} /> Excel
            </button>
            <button className="btn btn-secondary" onClick={() => handleExport('csv')} style={{ padding: '8px 14px' }}>
              <Icon name="download" size={14} /> CSV
            </button>
            <button className="btn btn-secondary" onClick={() => handleExport('image')} style={{ padding: '8px 14px' }}>
              <Icon name="download" size={14} /> Image
            </button>
          </div>
        </div>
      </div>

      {/* Records table */}
      <div className="card" style={{ padding: '0', overflow: 'hidden' }}>
        <div style={{ overflowX: 'auto' }}>
          {loading ? (
            <div className="empty-state" style={{ padding: '40px' }}>Loading your attendance…</div>
          ) : filtered.length === 0 ? (
            <div className="empty-state" style={{ padding: '40px' }}>
              No attendance records found between {fromDate} and {toDate}. Mark attendance using the Mark Attendance page.
            </div>
          ) : (
            <table className="data-table">
              <thead>
                <tr>
                  <th className="hide-mobile">Date</th>
                  <th>Class</th>
                  <th className="hide-mobile">Subject</th>
                  <th>Day</th>
                  <th>Period</th>
                  <th>Presence</th>
                  <th>Status</th>
                  <th className="hide-mobile">Marked At</th>
                  <th className="hide-mobile">Approved By</th>
                </tr>
              </thead>
              <tbody>
                {filtered.map(r => (
                  <tr key={r.id}>
                    <td className="hide-mobile">{r.scheduledDate}</td>
                    <td><span className="badge primary">{r.className}</span></td>
                    <td className="hide-mobile">{r.subject || '—'}</td>
                    <td>{r.day}</td>
                    <td>{ORDINALS[r.periodIndex] || (r.periodIndex + 1) + 'th'}</td>
                    <td>
                      <span className={`badge badge-${presenceMeta[r.presence]?.cls || 'info'}`}>
                        {presenceMeta[r.presence]?.label || 'Present'}
                      </span>
                    </td>
                    <td>
                      <span className={`badge badge-${statusMeta[r.status]?.cls || 'info'}`}>
                        {r.status === 'absent' || r.presence === 'absent' ? '—' : (statusMeta[r.status]?.label || r.status)}
                      </span>
                    </td>
                    <td className="hide-mobile" style={{ fontSize: '0.82rem', color: 'var(--gray)' }}>{r.markedAt}</td>
                    <td className="hide-mobile" style={{ fontSize: '0.82rem', color: 'var(--gray)' }}>{r.approvedBy || '—'}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
        </div>
      </div>
    </div>
  );
}

export default MyAttendance;